name = "CubeGraph"
version = "0.1.0"
defaultTargets = ["cubegraph"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "CubeGraph"

[[lean_exe]]
name = "cubegraph"
root = "Main"
