/-
  CubeGraph/Z2Reflection.lean
  ℤ/2 reflections on cube vertices.

  The negation of literal xᵢ corresponds to flipping bit i in the vertex
  encoding — a ℤ/2 reflection on axis i. The 8 vertices of a cube carry
  the action of the group (ℤ/2)³ generated by the three single-axis reflections.

  NEW DEFINITIONS:
  - flipBit: ℤ/2 reflection on a single axis (XOR with 1 <<< i)

  NEW THEOREMS:
  - flipBit_involutive:  σᵢ ∘ σᵢ = id
  - flipBit_vertexBit:   σᵢ flips exactly bit i, preserves other bits
  - flipBit_comm:         σᵢ ∘ σⱼ = σⱼ ∘ σᵢ  ((ℤ/2)³ is abelian)
  - complement_eq_flipAll: complementVertex = σ₀ ∘ σ₁ ∘ σ₂

  See: theory/foundations/02-clause-space.md (polarity encoding)
  See: experiments-ml/019_.../brainstorm/RANK1-CONVERGENCE.md §16 (geometric view)
  See: experiments-ml/019_.../brainstorm/PLAN-L6-Z2Reflection.md (plan)
-/

import CubeGraph.CNF

open Cube (vertexBit)
open CubeGraph (complementVertex)

/-- Flip bit i of vertex v: the ℤ/2 reflection on axis i.
    Negating literal xᵢ is exactly this operation on the vertex encoding.
    Formally: flipBit v i = v XOR (1 <<< i). -/
def flipBit (v : Vertex) (i : Fin 3) : Vertex :=
  ⟨v.val ^^^ (1 <<< i.val), by revert v i; native_decide⟩

/-- flipBit is involutive: reflecting twice on the same axis = identity. σᵢ² = e. -/
theorem flipBit_involutive (v : Vertex) (i : Fin 3) :
    flipBit (flipBit v i) i = v := by
  revert v i; native_decide

/-- flipBit flips exactly bit i, preserving all other bits. -/
theorem flipBit_vertexBit (v : Vertex) (i j : Fin 3) :
    vertexBit (flipBit v i) j =
    if i = j then !vertexBit v j else vertexBit v j := by
  revert v i j; native_decide

/-- Reflections on different axes commute: (ℤ/2)³ is abelian. σᵢσⱼ = σⱼσᵢ. -/
theorem flipBit_comm (v : Vertex) (i j : Fin 3) :
    flipBit (flipBit v i) j = flipBit (flipBit v j) i := by
  revert v i j; native_decide

/-- complementVertex = composition of all three reflections: σ₀ ∘ σ₁ ∘ σ₂.
    Decomposes the existing 7 − v definition into three elementary ℤ/2 reflections. -/
theorem complement_eq_flipAll (v : Vertex) :
    complementVertex v =
    flipBit (flipBit (flipBit v ⟨0, by omega⟩) ⟨1, by omega⟩) ⟨2, by omega⟩ := by
  revert v; native_decide
